azs:
- cloud_properties:
    datacenters:
    - clusters:
      - Cluster:
          resource_pool: null
      name: az1
  cpi: 7538cd480322856a1af6
  name: az1
compilation:
  az: az1
  env:
    bosh:
      password: $6$dc9dfa0da...zCOb/
  network: infrastructure
  reuse_compilation_vms: true
  vm_extensions: []
  vm_type: large.cpu
  workers: 4
disk_types:
- cloud_properties:
    type: thin
  disk_size: 1024
  name: "1024"
- cloud_properties:
    type: thin
  disk_size: 2048
  name: "2048"
- cloud_properties:
    type: thin
  disk_size: 5120
  name: "5120"
- cloud_properties:
    type: thin
  disk_size: 10240
  name: "10240"
- cloud_properties:
    type: thin
  disk_size: 20480
  name: "20480"
- cloud_properties:
    type: thin
  disk_size: 30720
  name: "30720"
- cloud_properties:
    type: thin
  disk_size: 51200
  name: "51200"
- cloud_properties:
    type: thin
  disk_size: 76800
  name: "76800"
- cloud_properties:
    type: thin
  disk_size: 102400
  name: "102400"
- cloud_properties:
    type: thin
  disk_size: 153600
  name: "153600"
- cloud_properties:
    type: thin
  disk_size: 204800
  name: "204800"
- cloud_properties:
    type: thin
  disk_size: 307200
  name: "307200"
- cloud_properties:
    type: thin
  disk_size: 512000
  name: "512000"
- cloud_properties:
    type: thin
  disk_size: 768000
  name: "768000"
- cloud_properties:
    type: thin
  disk_size: 1048576
  name: "1048576"
- cloud_properties:
    type: thin
  disk_size: 2097152
  name: "2097152"
- cloud_properties:
    type: thin
  disk_size: 3145728
  name: "3145728"
- cloud_properties:
    type: thin
  disk_size: 4194304
  name: "4194304"
- cloud_properties:
    type: thin
  disk_size: 6291456
  name: "6291456"
- cloud_properties:
    type: thin
  disk_size: 8388608
  name: "8388608"
- cloud_properties:
    type: thin
  disk_size: 10485760
  name: "10485760"
- cloud_properties:
    type: thin
  disk_size: 12582912
  name: "12582912"
- cloud_properties:
    type: thin
  disk_size: 14680064
  name: "14680064"
- cloud_properties:
    type: thin
  disk_size: 16777216
  name: "16777216"
- cloud_properties:
    type: thin
  disk_size: 20971520
  name: "20971520"
- cloud_properties:
    type: thin
  disk_size: 25165824
  name: "25165824"
- cloud_properties:
    type: thin
  disk_size: 29360128
  name: "29360128"
- cloud_properties:
    type: thin
  disk_size: 33554432
  name: "33554432"
networks:
- name: infrastructure
  subnets:
  - azs:
    - az1
    cloud_properties:
      name: VM Network
    dns:
    - 192.168.1.252
    gateway: 10.0.0.1
    range: 10.0.0.0/24
    reserved:
    - 10.0.0.0-10.0.0.20
    static:
    - 10.0.0.30
  type: manual
- name: pks
  subnets:
  - azs:
    - az1
    cloud_properties:
      name: VM Network
    dns:
    - 192.168.1.252
    gateway: 10.0.0.1
    range: 10.0.0.0/22
    reserved:
    - 10.0.0.0-10.0.0.255
    static: []
  type: manual
vm_extensions:
- cloud_properties: {}
  name: public_ip
vm_types:
- cloud_properties:
    cpu: 1
    disk: 8192
    ram: 512
  name: nano
- cloud_properties:
    cpu: 1
    disk: 8192
    ram: 1024
  name: micro
- cloud_properties:
    cpu: 2
    disk: 8192
    ram: 1024
  name: micro.ram
- cloud_properties:
    cpu: 1
    disk: 8192
    ram: 2048
  name: small
- cloud_properties:
    cpu: 1
    disk: 16384
    ram: 2048
  name: small.disk
- cloud_properties:
    cpu: 2
    disk: 8192
    ram: 4096
  name: medium
- cloud_properties:
    cpu: 1
    disk: 8192
    ram: 8192
  name: medium.mem
- cloud_properties:
    cpu: 2
    disk: 32768
    ram: 4096
  name: medium.disk
- cloud_properties:
    cpu: 4
    disk: 8192
    ram: 2048
  name: medium.cpu
- cloud_properties:
    cpu: 2
    disk: 16384
    ram: 8192
  name: large
- cloud_properties:
    cpu: 1
    disk: 16384
    ram: 16384
  name: large.mem
- cloud_properties:
    cpu: 2
    disk: 65536
    ram: 8192
  name: large.disk
- cloud_properties:
    cpu: 4
    disk: 16384
    ram: 4096
  name: large.cpu
- cloud_properties:
    cpu: 4
    disk: 32768
    ram: 16384
  name: xlarge
- cloud_properties:
    cpu: 2
    disk: 32768
    ram: 32768
  name: xlarge.mem
- cloud_properties:
    cpu: 4
    disk: 131072
    ram: 16384
  name: xlarge.disk
- cloud_properties:
    cpu: 8
    disk: 32768
    ram: 8192
  name: xlarge.cpu
- cloud_properties:
    cpu: 8
    disk: 65536
    ram: 32768
  name: 2xlarge
- cloud_properties:
    cpu: 4
    disk: 65536
    ram: 65536
  name: 2xlarge.mem
- cloud_properties:
    cpu: 8
    disk: 262144
    ram: 32768
  name: 2xlarge.disk
- cloud_properties:
    cpu: 16
    disk: 65536
    ram: 16384
  name: 2xlarge.cpu
