product-name: p-clamav
network-properties: null
product-properties:
  .properties.action:
    value: notify
  .properties.daily_db_check_frequency:
    value: ((daily_db_check_frequency))
  .properties.database_mirrors:
    value: private_mirror
  .properties.database_mirrors.private_mirror.mirror_urls:
    value: ((database_mirrors_private_mirror_mirror_urls))
  .properties.enforce_cpu_limit:
    value: disabled
  .properties.exclude_paths:
    value: ((exclude_paths))
  .properties.memory_limit:
    value: ((memory_limit))
  .properties.on_access:
    value: ((on_access))
  .properties.schedule_interval:
    value: daily
  .properties.schedule_interval.daily.first_scheduled_scan_time:
    value: ((schedule_interval_daily_first_scheduled_scan_time))
  .properties.schedule_interval.daily.last_scheduled_scan_time:
    value: ((schedule_interval_daily_last_scheduled_scan_time))
  .properties.use_proxy:
    value: disabled
